### ISSUE TITLE
Center vs. Starting Ephemeris Time

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/pfeffernusse#4]
Currently, the spec requires starting ephemeris time. For a line scan we also need line rates or a single delta time. For a framing sensor we need the center time (or the stop time from which the start can be computed). Not sure the best way to handle this, but the spec needs to be updated.

Tagging @Kelvinrr and @jessemapel to discuss.

**Comment by jessemapel** [comment]
For the framing camera we want both the center time and the exposure duration. So, I'd say we go with starting time period and then we can compute the center time from the starting time plus half the exposure duration.

**Comment by jessemapel** [comment]
Although I'm not sure if CSM supports computing things at different times. If it doesn't that's a problem for computing pixel fov across the exosure

**Comment by jlaura** [comment]
Currently time is handled in a weird way in the [specification](https://github.com/USGS-Astrogeology/pfeffernusse/blob/master/swagger.yaml).

For a framer we need: (1) start time and (2) exposure duration.
For a LS we need: (1) start time and (2) line rate OR (1) start time and (2) dt_ephemeris.

We current have the following: dt_quaternion, t0_ephemeris (center image time), dt_ephemeris (time between ephemeris pts), line_scan_rate, starting_ephemeris_time, center_ephemeris_time.

I would propose that we move to a `time` object that can accept one of three sub-objects:
```
Time_Instantaneous
  type: object 
  title: InstantaneousExposure
  description: An instantaneous frame exposure
  required:
    - start_time
    - exposure_time
    - unit
  properties:
    start_time:
      type: number
    exposure_time:
      type: number
    unit: 
      type: string

Time_FixedRate
  type: object 
  title: FixedRate
  description: A fixed rate time
  required:
    - start_time
    - exposure_rate
    - unit
  properties:
    start_time:
      type: number
    exposure_rate:
      type: number
    unit: 
      type: string
 
Time_VariableRate
  type: object
  title: Variable Rate Line Scan
  required:
  - start_time
  - exposure_rate OR line_rate
  - unit
 properties:
    start_time:
      type: number
    exposure_rate:
      type: array (n,1)
    line_rate:
      type: array (n,3)
    unit: 
      type: string
```
